version: "v2.0"
name: "BK-CI GITHUB PR CHECK"

on:
  mr:
    target-branches:  [ "master" ]

stages:
- name: "PR检查"
  label:
  - "Build"
  jobs:
    job_1:
      name: "源代码规范性检查"
      runs-on:
        needs:
          jdk: "1.8.0_161"
      steps:
        - checkout: self
          name: "预合并 BK-CI代码"
          with:
            usernameConfig: mingshewhe
            userEmailConfig: mingshewhe@tencent.com
            enableGitLfs: false
          
        - name: "kotlin代码规范检查"
          run: |
            cd src/backend/ci
            wget https://github.com/pinterest/ktlint/releases/download/0.29.0/ktlint -O ktlint
            java -jar ktlint "**/src/**/*.kt" --reporter=plain,output=report/ktlint-report.txt
        
        - uses: uploadReport@1.*
          name: 归档报告
          with:
            fileDir: src/backend/ci/report
            indexFile: ktlint-report.txt
            indexFileCharset: UTF-8
            reportName: ktlint-report
            isParallel: false
            isSendEmail: false

