spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: dispatch-kubernetes{service-suffix}
    desc: DevOps Dispatch kubernetes Service
    version: 4.0.0
    packageName: com.tencent.devops.dispatch.kubernetes

server:
  port: 21948
